title: Project
pages: false
files:
  sortable: true
  fields:
    caption:
      label: Caption (optional)
      type: text
    _lineOne:
      type: line
    _infoOne:
      label: Choosing your layout
      type: info
      text: >
        Project images are full width by default. Selecting one of the options below will float the images according to the size shown, but remember to pair one ratio with another. For example: half-size images should be ordered next to each other and likewise for third and two-thirds images.


        Layout ratios do not affect thumbnails or homepage feature images.
    layout:
      label: Layout Options/Ratios
      type: radio
      default: full
      options:
        full: Full width
        half: Half size
        third: One third
        twothirds: Two thirds

fields:
  _headerOne:
    label: Section – Images
    type: headline
  featuredFilename:
    label: Feature & Social Image (defaults to image named 'feature')
    type: select
    options: images
    help: >
      – this image will be displayed when shared on FaceBook and Twitter, so make sure it's set. Use the <a target="_blank" href="https://developers.facebook.com/tools/debug/">FaceBook debug tool</a> and <a target="_blank" href="https://cards-dev.twitter.com/validator">Twitter Card Validator</a> to test before you share.
  thumbFilename:
    label: Thumbnail Image (defaults to image named 'thumb')
    type: select
    options: images
  _infoOne:
    type: info
    text: >
      **Images sizes:** <br>
      – Thumbnail: 466px <br>
      – Feature: 680px <br>
      – All others: 1400px (full), 680px (half), 440px (one third), 920px (two thirds)

  project_images:
    label: Project Images
    type: structure
    style: table
    fields:
      filename:
        label: Image
        type: select
        options: images
      caption:
        label: Caption
        type: text
        help: >
          – HTML and <a href="http://daringfireball.net/projects/markdown/syntax">markdown</a> supported
      layout:
        label: Layout Options/Ratios
        type: radio
        default: full
        options:
          full: Full width
          half: Half size
          third: One third
          twothirds: Two thirds


  _headerTwo:
    label: Section - Project Information
    type: headline
  title:
    label: Project Title
    type:  text
  summary:
    label: Project Summary
    type:  text
  intro:
    label: Introduction
    type:  textarea
  details:
    label: Details
    type: textarea
