title: Site
pages:
  sortable: true
  max: 5
files: true
fields:

  _headerOne:
    label: Site Configuration
    type: headline
  title:
    label: Site Name
    type: text
    width: 1/2
  author:
    label: Your Name
    type: text
    width: 1/2
  email:
    label: Contact Email Address
    type: email
    width: 1/2
  phone:
    label: Contact Phone Number
    type: text
    width: 1/2
  analytics:
    label:  Google Analytics Tracking code
    type: text
    default: UA-XXXXXX-X
    width: 1/2
  description:
    label: Site Description (SEO meta)
    type:  text
  keywords:
    label: Site Keywords (SEO meta)
    type:  tags
  copyright:
    label: Copyright
    type:  textarea

  _headerTwo:
    label: Twitter Settings
    type: headline
  _infoTwo:
    label: &nbsp;
    type: info
    text: >
      Turning off the stream will not display any tweets, anywhere on the site, from your account.
  showTweets:
    label: Show Twitter Stream?
    type: toggle
    text: yes/no
  _infoThree:
    label: &nbsp;
    type: info
    text: >
      Only tweets with this hashtag will be displayed. If it's left blank all your tweets will
      be displayed by default.
  tweetFilter:
    label: Tweet-Filter Keyword
    type: text

  header_contact_ooter:
    label: Contact Footer
    type: headline
  info_contact_footer:
    label: &nbsp;
    type: info
    text: >
      You change how your email and phone number links are displayed from the fields below, but the actual email address and phone number can be changed within the global site options.
  contact_title:
    label: Contact Footer Title
    type: text
  email_text:
    label: Email Text
    type: text
    width: 1/2
  phone_text:
    label: Phone Text
    type: text
    width: 1/2
  contact_text:
    label: Text
    type:  textarea
  contact_image_filename:
    label: Contact Image
    type: image

  header_social_links:
    label: Social Links
    type: headline
  info_social_links:
    type: info
    text: >
      These links appear in the Contact Footer as well as the Contact page
  social_links:
    label: Social Links
    type: structure
    style: table
    limit: 3
    fields:
      title:
        label: Title
        type: text
      url:
        label: URL
        type: url
